blank_issues_enabled: false
contact_links:
  - name: ğŸš€ GitHub Discussions
    url: https://github.com/nodgu/nodgu-server/discussions
    about: ì¼ë°˜ì ì¸ ì§ˆë¬¸ì´ë‚˜ í† ë¡ ì€ Discussionsë¥¼ ì´ìš©í•´ì£¼ì„¸ìš”! 